### ISSUE TITLE
Rocket chat is crashing

### ISSUE THREAD

**Issue by fridokus** [fridokus/erichat#1]
```
eselnts1487> kc get pod                                                                                             # /repo/ezfrios/erichat
NAME                               READY   STATUS             RESTARTS   AGE
mongo-dc768c984-7k65t              1/1     Running            0          5m11s
nfs-provisioner-54db5878bf-2l6vx   1/1     Running            0          28m
rocketchat-6f9777cbb6-qgthv        0/1     CrashLoopBackOff   5          5m22s

```

**Comment by fridokus** [comment]
```
eselnts1487> kc logs -p rocketchat-6f9777cbb6-qgthv                                                                 # /repo/ezfrios/erichat
/app/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 10.100.74.39:27017]
    at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```
